import { createHash } from 'crypto';
import type {
  LLMProvider,
  LLMRequest,
  LLMGenerationResult,
  LLMStreamResult,
  RuntimeMode,
  ProviderHealth,
} from '../providerTypes.js';

function deterministicHash(input: string): number {
  const digest = createHash('sha256').update(input).digest('hex').slice(0, 8);
  return Number.parseInt(digest, 16);
}

function buildDeterministicResponse(request: LLMRequest): string {
  const transcript = request.messages
    .map((m) => `${m.role}:${m.content}`)
    .join('\n')
    .slice(-2000);
  const hash = deterministicHash(transcript);

  const starter = [
    'Here is a deterministic test response.',
    'This output is generated by the mock provider for repeatable QA runs.',
    'Use it to validate routing, persistence, UI behavior, and safety gates.',
  ];

  const variants = [
    'Next step: validate message persistence and state reconciliation.',
    'Next step: run the safety non-regression checks before release.',
    'Next step: export evidence pack and compare config snapshots.',
    'Next step: inspect latency p50/p95 from autonomy events.',
  ];

  const selected = variants[hash % variants.length];
  return `${starter.join(' ')}\n\nDeterministic key: ${hash}.\n${selected}`;
}

export class MockProvider implements LLMProvider {
  readonly id = 'mock' as const;

  async generateChat(request: LLMRequest, mode: RuntimeMode): Promise<LLMGenerationResult> {
    const started = Date.now();
    console.log(
      `[TEST_MODE][MOCK] generateChat model=${request.model || 'mock-v1'} temperature=${request.temperature ?? 0} maxTokens=${request.maxTokens ?? 500}`
    );
    const content = buildDeterministicResponse(request);
    return {
      content,
      metadata: {
        provider: this.id,
        mode,
        model: request.model || 'mock-v1',
        latencyMs: Date.now() - started,
        temperature: request.temperature ?? 0,
        maxTokens: request.maxTokens ?? 500,
      },
    };
  }

  async streamChat(request: LLMRequest, mode: RuntimeMode): Promise<LLMStreamResult> {
    const started = Date.now();
    console.log(
      `[TEST_MODE][MOCK] streamChat model=${request.model || 'mock-v1'} temperature=${request.temperature ?? 0} maxTokens=${request.maxTokens ?? 500}`
    );
    const content = buildDeterministicResponse(request);
    const chunks = content.split(/(\s+)/).filter(Boolean);

    const stream = (async function* () {
      for (const chunk of chunks) {
        yield chunk;
      }
    })();

    return {
      stream,
      metadata: {
        provider: this.id,
        mode,
        model: request.model || 'mock-v1',
        latencyMs: Date.now() - started,
        temperature: request.temperature ?? 0,
        maxTokens: request.maxTokens ?? 500,
      },
    };
  }

  async healthCheck(): Promise<ProviderHealth> {
    return { status: 'ok', details: 'Deterministic mock provider is available' };
  }
}
